### ISSUE TITLE
Recent commit broke state_reconstruction

### ISSUE THREAD

**Issue by jonaswinklmann** [david-wei/libics#6]
Commit [core.data.arrays.ArrayData: Add __array_function__](https://github.com/david-wei/libics/commit/185a81cb58609092fd82ba70a5c7a5d7735e5bb7) broke interplay with state_reconstruction.

The new function __array_function__(self, func, types, args, kwargs) throws an "AttributeError: 'list' object has no attribute 'shape'" when numpy.broadcast_arrays is cast in code cell \[10\] in [psf+trafo_estimation.ipynb](https://github.com/david-wei/state_reconstruction/blob/main/scripts/psf%2Btrafo_estimation.ipynb). The numpy function does indeed return a list of arrays instead of an array.

Tested using Python 3.11.5.

**Comment by david-wei** [comment]
Fixed in commit [core.data.arrays.__array_function__: Bugfix](https://github.com/david-wei/libics/commit/c87209951190b6a7c7f0e3513b47b09af2a7cd5c).
