### ISSUE TITLE
Functions trapz and cumtrapz have been removed in Scipy 1.14.0.

### ISSUE THREAD

**Issue by jonaswinklmann** [david-wei/libics#8]
Deprecated functions trapz and cumtrapz in scipy.integrate have been removed in Scipy 1.14.0.
They are used in libics/tools/math/calculus.py (https://github.com/david-wei/libics/blob/master/libics/tools/math/calculus.py) and need to be replaced with trapezoid and cumulative_trapezoid respectively.

**Comment by david-wei** [comment]
Fixed in commit [tools.math.calculus: Fix for scipy update](https://github.com/david-wei/libics/commit/9d2be98580b2a944db277d5071618e88177fec6c).
